from __future__ import annotations

import shutil
import uuid
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from visionguard.config import (
    SAFETY_CLASS_NAME_MAPPING,
    SAFETY_REMOVED_CLASSES,
    SAFETY_TARGET_CLASSES,
    DatasetRemapConfig,
)
from visionguard.dataset import (
    DatasetDefinition,
    bbox_validation_error,
    collect_split_images,
    label_path_for_image,
    load_dataset_definition,
)
from visionguard.reporting import write_class_remap_reports

OUTPUT_SPLIT_NAMES = {"train": "train", "val": "valid", "test": "test"}


def _paths_overlap(first: Path, second: Path) -> bool:
    return first == second or first in second.parents or second in first.parents


def _validate_mapping(class_names: dict[int, str]) -> dict[int, int | None]:
    source_names = set(class_names.values())
    configured_names = set(SAFETY_CLASS_NAME_MAPPING) | set(SAFETY_REMOVED_CLASSES)
    missing = sorted(source_names - configured_names)
    unused = sorted(configured_names - source_names)
    if missing:
        raise ValueError(
            "Source data.yaml contains classes without a remapping rule: " + ", ".join(missing)
        )
    if unused:
        raise ValueError(
            "Configured remapping classes are absent from source data.yaml: " + ", ".join(unused)
        )

    target_ids = {name: class_id for class_id, name in enumerate(SAFETY_TARGET_CLASSES)}
    return {
        old_id: target_ids[SAFETY_CLASS_NAME_MAPPING[old_name]]
        if old_name in SAFETY_CLASS_NAME_MAPPING
        else None
        for old_id, old_name in class_names.items()
    }


def _relative_image_path(image_path: Path, definition: DatasetDefinition, split: str) -> Path:
    for source in definition.split_sources[split]:
        if not source.is_dir():
            continue
        try:
            return image_path.relative_to(source)
        except ValueError:
            continue
    return Path(image_path.name)


def _remap_label(
    source_label: Path,
    destination_label: Path,
    class_names: dict[int, str],
    id_mapping: dict[int, int | None],
) -> tuple[Counter[str], Counter[str], int, bool]:
    try:
        lines = source_label.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError) as exc:
        raise ValueError(f"Cannot read YOLO label as UTF-8: {source_label}: {exc}") from exc

    old_counts: Counter[str] = Counter()
    new_counts: Counter[str] = Counter()
    removed_count = 0
    output_lines: list[str] = []
    for line_number, raw_line in enumerate(lines, 1):
        line = raw_line.strip()
        if not line:
            continue
        fields = line.split()
        if len(fields) != 5:
            raise ValueError(
                f"Invalid YOLO label at {source_label}:{line_number}: expected 5 values, "
                f"found {len(fields)}."
            )
        try:
            old_id = int(fields[0])
        except ValueError as exc:
            raise ValueError(
                f"Invalid class ID at {source_label}:{line_number}: '{fields[0]}'."
            ) from exc
        if old_id not in class_names:
            raise ValueError(
                f"Class ID {old_id} at {source_label}:{line_number} is not declared in data.yaml."
            )
        try:
            bbox = [float(value) for value in fields[1:]]
        except ValueError as exc:
            raise ValueError(f"Non-numeric bounding box at {source_label}:{line_number}.") from exc
        bbox_error = bbox_validation_error(bbox)
        if bbox_error:
            raise ValueError(f"Invalid bounding box at {source_label}:{line_number}: {bbox_error}.")

        old_name = class_names[old_id]
        old_counts[old_name] += 1
        new_id = id_mapping[old_id]
        if new_id is None:
            removed_count += 1
            continue
        new_name = SAFETY_TARGET_CLASSES[new_id]
        new_counts[new_name] += 1
        output_lines.append(" ".join((str(new_id), *fields[1:])))

    destination_label.parent.mkdir(parents=True, exist_ok=True)
    destination_label.write_text(
        "\n".join(output_lines) + ("\n" if output_lines else ""), encoding="utf-8"
    )
    return old_counts, new_counts, removed_count, not output_lines


def _write_data_yaml(staging_dir: Path, source_data_path: Path) -> None:
    data = {
        "path": ".",
        "train": "train/images",
        "val": "valid/images",
        "test": "test/images",
        "nc": len(SAFETY_TARGET_CLASSES),
        "names": {class_id: name for class_id, name in enumerate(SAFETY_TARGET_CLASSES)},
        "source": {
            "data_yaml": str(source_data_path),
            "note": "Generated by VisionGuard's non-destructive class remapping pipeline.",
        },
    }
    (staging_dir / "data.yaml").write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )


def _copy_source_metadata(source_root: Path, staging_dir: Path) -> list[str]:
    copied: list[str] = []
    for source_file in sorted(source_root.glob("README*")):
        if source_file.is_file():
            destination = staging_dir / source_file.name
            shutil.copy2(source_file, destination)
            copied.append(source_file.name)
    return copied


def remap_dataset(config: DatasetRemapConfig) -> dict[str, Any]:
    """Create a clean YOLO dataset copy using the configured safety class taxonomy."""
    config = config.resolved()
    definition = load_dataset_definition(config.data_path)
    if _paths_overlap(definition.root, config.output_dir):
        raise ValueError(
            f"Source and output directories must not overlap: {definition.root} / {config.output_dir}"
        )
    if config.output_dir.exists():
        raise FileExistsError(
            f"Output directory already exists and will not be overwritten: {config.output_dir}"
        )
    id_mapping = _validate_mapping(definition.class_names)
    staging_dir = config.output_dir.parent / f".{config.output_dir.name}.tmp-{uuid.uuid4().hex}"
    staging_dir.mkdir(parents=True)

    old_counts: Counter[str] = Counter()
    new_counts: Counter[str] = Counter()
    empty_label_images: list[dict[str, str]] = []
    split_stats: dict[str, dict[str, int]] = {}
    seen_destinations: set[Path] = set()
    try:
        for split, output_split in OUTPUT_SPLIT_NAMES.items():
            images = collect_split_images(definition, split)
            split_removed = 0
            split_source_annotations = 0
            split_written_annotations = 0
            split_empty_labels = 0
            for image_path in images:
                if not image_path.is_file():
                    raise FileNotFoundError(f"Source image does not exist: {image_path}")
                relative_path = _relative_image_path(image_path, definition, split)
                destination_image = staging_dir / output_split / "images" / relative_path
                if destination_image in seen_destinations:
                    raise ValueError(
                        f"Multiple source images map to the same output path: {destination_image}"
                    )
                seen_destinations.add(destination_image)
                destination_image.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(image_path, destination_image)

                source_label = label_path_for_image(image_path, definition.root)
                if not source_label.is_file():
                    raise FileNotFoundError(f"Source image has no matching label: {image_path}")
                destination_label = (
                    staging_dir / output_split / "labels" / relative_path
                ).with_suffix(".txt")
                label_old, label_new, removed, is_empty = _remap_label(
                    source_label,
                    destination_label,
                    definition.class_names,
                    id_mapping,
                )
                old_counts.update(label_old)
                new_counts.update(label_new)
                split_removed += removed
                split_source_annotations += sum(label_old.values())
                split_written_annotations += sum(label_new.values())
                if is_empty:
                    split_empty_labels += 1
                    empty_label_images.append(
                        {
                            "split": output_split,
                            "source_image": str(image_path),
                            "clean_image": str(
                                config.output_dir / output_split / "images" / relative_path
                            ),
                        }
                    )

            split_stats[output_split] = {
                "images": len(images),
                "source_annotations": split_source_annotations,
                "written_annotations": split_written_annotations,
                "removed_annotations": split_removed,
                "empty_label_images": split_empty_labels,
            }

        _write_data_yaml(staging_dir, config.data_path)
        metadata_files = _copy_source_metadata(definition.root, staging_dir)
        report = {
            "generated_at": datetime.now(UTC).isoformat(),
            "source_data_yaml": str(config.data_path),
            "source_dataset_root": str(definition.root),
            "output_dataset_root": str(config.output_dir),
            "source_dataset_modified": False,
            "target_classes": {
                str(class_id): name for class_id, name in enumerate(SAFETY_TARGET_CLASSES)
            },
            "mapping": dict(SAFETY_CLASS_NAME_MAPPING),
            "removed_classes": sorted(SAFETY_REMOVED_CLASSES),
            "old_class_counts": {
                name: old_counts[name] for name in definition.class_names.values()
            },
            "new_class_counts": {name: new_counts[name] for name in SAFETY_TARGET_CLASSES},
            "removed_glasses_annotations": old_counts["glasses"],
            "empty_label_images_count": len(empty_label_images),
            "empty_label_images": empty_label_images,
            "splits": split_stats,
            "copied_metadata_files": metadata_files,
        }
        write_class_remap_reports(report, staging_dir)
        staging_dir.replace(config.output_dir)
        return report
    except Exception:
        shutil.rmtree(staging_dir, ignore_errors=True)
        raise
